#pragma once
// Auto-generated by analysis/seq_to_header.py from home.json. DO NOT EDIT.
#include "motion.h"

static const MotionFrame home_frames[] = {
  {{476,511,524,504,564,467,526,545}, 1000},
};
static const Motion home_motion = { "home", home_frames, 1 };

