#pragma once
// Auto-generated by analysis/seq_to_header.py. DO NOT EDIT.
// 全Teaching動作のレジストリ。prodはこれをincludeしてボタン生成＋再生する。
#include "motion.h"
#include "home.h"

static const Motion* const ALL_MOTIONS[] = { &home_motion };
static const int N_MOTIONS = sizeof(ALL_MOTIONS)/sizeof(ALL_MOTIONS[0]);
