#!/usr/bin/env python3
"""seq_to_header.py — Teaching シーケンスJSON → prod用Cヘッダ変換

手作りでエクスポートした analysis/sequences/*.json を、prod(src/main.cpp)が
動作ボタンとして再生できる src/motions/<name>.h と src/motions/motions_all.h に
変換する。これが「手作りの動き → 本編の操作ボタン」の橋渡し。

使い方（リポジトリ直下で）:
    python3 analysis/seq_to_header.py

JSON形式（teachファームの ⬇エクスポート 出力。自己完結）:
    { "name":"home","defMs":1000,
      "calib":{...}, "frames":[ {"t":1000,"raw":[...8...]}, ... ] }

生成物:
    src/motions/<stem>.h        各シーケンスのコマ配列とMotion定義
    src/motions/motions_all.h   全Motionを束ねたレジストリ ALL_MOTIONS[] / N_MOTIONS
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEQ_DIR = ROOT / "analysis" / "sequences"
OUT_DIR = ROOT / "src" / "motions"


def ident(stem: str) -> str:
    """ファイル名(stem)を安全なC識別子に変換する。"""
    s = re.sub(r"[^a-zA-Z0-9_]", "_", stem).lower()
    if not s or s[0].isdigit():
        s = "m_" + s
    return s


def clamp_raw(v: int) -> int:
    return max(0, min(1023, int(v)))


def gen_one(path: Path) -> tuple[str, str]:
    """1つのJSON→ヘッダ文字列。(C識別子, 生成ファイル名)を返す。"""
    data = json.loads(path.read_text(encoding="utf-8"))
    stem = path.stem
    name = ident(stem)
    disp = str(data.get("name", stem))
    def_ms = int(data.get("defMs", 600))
    frames = data.get("frames", [])

    lines = []
    lines.append("#pragma once")
    lines.append(f"// Auto-generated by analysis/seq_to_header.py from {path.name}. DO NOT EDIT.")
    lines.append('#include "motion.h"')
    lines.append("")
    lines.append(f"static const MotionFrame {name}_frames[] = {{")
    for fr in frames:
        raw = fr.get("raw", [])
        if len(raw) != 8:
            raise ValueError(f"{path.name}: frame raw must have 8 values, got {len(raw)}")
        raw = [clamp_raw(x) for x in raw]
        t = int(fr.get("t", def_ms))
        rawstr = ",".join(str(x) for x in raw)
        lines.append(f"  {{{{{rawstr}}}, {t}}},")
    lines.append("};")
    lines.append(f'static const Motion {name}_motion = {{ "{disp}", {name}_frames, {len(frames)} }};')
    lines.append("")
    return name, "\n".join(lines)


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if not SEQ_DIR.exists():
        print(f"no sequences dir: {SEQ_DIR}")
        return 1

    jsons = sorted(p for p in SEQ_DIR.glob("*.json"))
    names = []
    for p in jsons:
        try:
            name, text = gen_one(p)
        except Exception as e:  # noqa: BLE001
            print(f"skip {p.name}: {e}", file=sys.stderr)
            continue
        (OUT_DIR / f"{p.stem}.h").write_text(text + "\n", encoding="utf-8")
        names.append((name, p.stem))
        print(f"  {p.name} -> src/motions/{p.stem}.h  ({name})")

    # レジストリ motions_all.h
    out = ["#pragma once",
           "// Auto-generated by analysis/seq_to_header.py. DO NOT EDIT.",
           "// 全Teaching動作のレジストリ。prodはこれをincludeしてボタン生成＋再生する。",
           '#include "motion.h"']
    for _, stem in names:
        out.append(f'#include "{stem}.h"')
    out.append("")
    if names:
        arr = ", ".join(f"&{n}_motion" for n, _ in names)
        out.append(f"static const Motion* const ALL_MOTIONS[] = {{ {arr} }};")
        out.append("static const int N_MOTIONS = sizeof(ALL_MOTIONS)/sizeof(ALL_MOTIONS[0]);")
    else:
        out.append("static const Motion* const ALL_MOTIONS[1] = { nullptr };  // 空時のダミー")
        out.append("static const int N_MOTIONS = 0;")
    (OUT_DIR / "motions_all.h").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote src/motions/motions_all.h  (N_MOTIONS={len(names)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
